# Generated by Django 4.2.11 on 2024-04-10 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="hospital",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="model_1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hospital_Name", models.CharField(max_length=100, null=True)),
                ("patient_Name", models.CharField(max_length=100, null=True)),
                ("doctor_Name", models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="model_2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hospital_Name", models.CharField(max_length=100, null=True)),
                ("patient_Name", models.CharField(max_length=100, null=True)),
                ("doctor_Name", models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="model_3",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hospital_Name", models.CharField(max_length=100, null=True)),
                ("patient_Name", models.CharField(max_length=100, null=True)),
                ("doctor_Name", models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
