# Generated by Django 4.2.11 on 2024-04-10 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="model_2", old_name="doctor_Name", new_name="doctor_Name1",
        ),
        migrations.RenameField(
            model_name="model_2", old_name="hospital_Name", new_name="hospital_Name1",
        ),
        migrations.RenameField(
            model_name="model_2", old_name="patient_Name", new_name="patient_Name1",
        ),
        migrations.RenameField(
            model_name="model_3", old_name="doctor_Name", new_name="doctor_Name2",
        ),
        migrations.RenameField(
            model_name="model_3", old_name="hospital_Name", new_name="hospital_Name2",
        ),
        migrations.RenameField(
            model_name="model_3", old_name="patient_Name", new_name="patient_Name2",
        ),
    ]
