# Generated by Django 4.2.11 on 2024-04-15 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_rename_doctor_name_model_2_doctor_name1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="model_1",
            name="Disease",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="model_1",
            name="specilization",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="model_2",
            name="Disease1",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="model_2",
            name="specilization1",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="model_3",
            name="Disease2",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="model_3",
            name="specilization2",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
