# Generated by Django 5.0.4 on 2024-04-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_model_1_disease_model_1_specilization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_1',
            name='age',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='model_1',
            name='gender',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='model_1',
            name='qualification',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='model_1',
            name='weight',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='model_2',
            name='age1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='model_2',
            name='gender1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='model_2',
            name='qualification1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='model_2',
            name='weight1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='model_3',
            name='age2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='model_3',
            name='gender2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='model_3',
            name='qualification2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='model_3',
            name='weight2',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
